import {
  MainStyleBoxRoot as BoxRoot,
  MainStyleFullContent as FullContent,
  MainStyleModalFooter as ModalFooter,
  MainStyleInfoWrapper as InfoWrapper,
  MainStyleLinks as Links,
  MainStyleFormWrapper as FormWrapper,
  MainStyleFormColumn as FormColumn,
  MainStyleCenterContent as CenterContent,
  MainStyleActivityContent as ActivityContent,
  MainStyleDropIcon as DropIcon,
  MainStyleMiddleContent as MiddleContent,
  MainStyleHomeContainer as HomeContainer,
  MainStyleDateWrapper as DateWrapper,
  MainStyleCloseModal as CloseModal,
  MainStyleScrollWrapper as ScrollWrapper,
  MainStyleDateContainer as DateContainer,
  MainStyleTabContent as TabContent,
  MainStyleButtonRelated as ButtonRelated,
  MainStyleSimpleButton as SimpleButton,
  MainStyleTopHeader as TopHeader,
  MainStyleTitle as Title,
  MainStyleCount as Count,
  MainStyleLimited as Limited
} from 'erxes-ui';

export {
  BoxRoot,
  FullContent,
  ModalFooter,
  InfoWrapper,
  Links,
  FormWrapper,
  FormColumn,
  CenterContent,
  ActivityContent,
  DropIcon,
  MiddleContent,
  HomeContainer,
  DateWrapper,
  CloseModal,
  ScrollWrapper,
  DateContainer,
  TabContent,
  ButtonRelated,
  SimpleButton,
  TopHeader,
  Title,
  Count,
  Limited
};
